### ISSUE TITLE
TODO list du projet

### ISSUE THREAD

**Issue by Heartbroken-Git** [Heartbroken-Git/Nono-1-X5I0030#1]
# TODO liste du projet *Réalisation des processeurs Nono-1 et Nono-2*

## Implémentation du Nono-1

- [x] Réaliser l'UAL
- [x] Réaliser le décodeur d'instructions
- [x] Réaliser le contrôleur de saut
- [x] Réaliser le banc de registres
- [x] Réaliser le module de sélection des registres
- [x] Implémenter la mémoire programme
- [x] Assembler le processeur Nono-1 à partir des pièces fabriquées précédemment

## Utilisation du Nono-1

- [x] Répondre à la question 1 sur rapport
- [x] Traduire en assembleur et en code machine *pgcd(int a, int b)*
- [x] Traduire en assembleur et en code machine *minMax(int arg, int a, int b)*
-  ~~Implémenter Nono-2~~ (pas le temps)

## Autres

- [ ] Rédiger le rapport
- [ ] Tester le processeur
- [x] Voir avec le professeur comment implémenter en vrai Nono-1
- [ ] Insérer une licence d'utilisation
- [ ] Faire une release correcte du projet (dans le sens GitHub du terme)
